name: sentinel-data
channels:
  - defaults
dependencies:
  - asn1crypto=0.24.0
  - astroid=2.2.5
  - blas=1.0
  - ca-certificates=2019.1.23
  - certifi=2019.3.9
  - cffi=1.12.3
  - chardet=3.0.4
  - cryptography=2.6.1
  - cycler=0.10.0
  - freetype=2.9.1
  - geos=3.7.1
  - idna=2.8
  - intel-openmp=2019.3
  - isort=4.3.19
  - jedi=0.13.3
  - kiwisolver=1.1.0
  - lazy-object-proxy=1.4.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libpng=1.6.37
  - libspatialindex=1.8.5
  - matplotlib=3.0.3
  - mccabe=0.6.1
  - mkl=2019.3
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - ncurses=6.1
  - numpy=1.16.3
  - numpy-base=1.16.3
  - openssl=1.1.1b
  - parso=0.4.0
  - pip=19.1.1
  - pycparser=2.19
  - pylint=2.3.1
  - pyopenssl=19.0.0
  - pyparsing=2.4.0
  - pyshp=2.1.0
  - pysocks=1.6.8
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2019.1
  - readline=7.0
  - requests=2.21.0
  - rtree=0.8.3
  - setuptools=41.0.1
  - shapely=1.6.4
  - six=1.12.0
  - sqlite=3.28.0
  - tk=8.6.8
  - tornado=6.0.2
  - urllib3=1.24.2
  - wheel=0.33.2
  - wrapt=1.11.1
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - greenlet==0.4.15
    - msgpack==0.6.1
    - neovim==0.3.1
    - pynvim==0.3.2
    - requests-cache==0.5.0
prefix: /usr/local/miniconda3/envs/sentinel-data

